### ISSUE TITLE
Advise how to encode lang attribute in title using lxml

### ISSUE THREAD

**Issue by TAlonglong** [steingod/mmd#73]
According to doc the 2.6 title has mandatory attribute xml:lang

I'm using lxml to generate my mmd xml file. Here is an minimal example

```
import lxml.etree as ET

root = ET.Element('tt')
tt = ET.SubElement(root, 'test')
tt.attrib['xml:lang'] = 'no'

print(ET.tostring(root, pretty_print=True).decode("utf-8"))
```

output:

```
Traceback (most recent call last):
  File "src/mini-xml.py", line 5, in <module>
    tt.attrib['xml:lang'] = 'no'
  File "src/lxml/etree.pyx", line 2429, in lxml.etree._Attrib.__setitem__
  File "src/lxml/apihelpers.pxi", line 585, in lxml.etree._setAttributeValue
  File "src/lxml/apihelpers.pxi", line 1744, in lxml.etree._attributeValidOrRaise
ValueError: Invalid attribute name 'xml:lang'
```

I know this is a lxml specific problem but I hope someone have an advice how I can do this.

**Comment by ferrighi** [comment]
You can maybe try
tt.set("{http://www.w3.org/XML/1998/namespace}lang", "en")?

**Comment by TAlonglong** [comment]
Ah, thank you @ferrighi. I knew it was a simple solution. I just could not find it.
